# Generated by Django 2.2.10 on 2020-03-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(db_index=True, max_length=64)),
                ('token', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=64)),
                ('serverid', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '推送注册信息',
                'db_table': 'fcm_token',
                'managed': False,
            },
        ),
    ]
