# Generated by Django 2.2.10 on 2020-03-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(db_index=True, default='', max_length=64)),
                ('serverid', models.IntegerField(default=0)),
                ('playerid', models.BigIntegerField(default=0)),
                ('device', models.CharField(default='', max_length=64)),
                ('order_id', models.CharField(db_column='orderId', default='', max_length=255)),
                ('product_id', models.CharField(db_column='productId', default='', max_length=64)),
                ('status', models.IntegerField(default=0)),
                ('tester', models.IntegerField(default=0)),
                ('platform', models.CharField(default='', max_length=64)),
                ('pay_way', models.CharField(default='', max_length=64)),
                ('time', models.DateTimeField(blank=True, db_column='purchaseTime', null=True)),
            ],
            options={
                'verbose_name_plural': '充值',
                'db_table': 'charge_order',
                'managed': False,
            },
        ),
    ]
